steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/nifty-charter-294516/coretest5', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/nifty-charter-294516/coretest5']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'coretest5', '--image', 'gcr.io/nifty-charter-294516/coretest5', '--region', 'us-east1', '--platform', 'managed']
images:
- gcr.io/nifty-charter-294516/coretest5
